// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Appointment struct {
	ID              int64       `json:"id"`
	PatientUsername string      `json:"patient_username"`
	DoctorUsername  string      `json:"doctor_username"`
	DoctorName      string      `json:"doctor_name"`
	AppointmentDate pgtype.Date `json:"appointment_date"`
	AppointmentTime string      `json:"appointment_time"`
	Specialty       string      `json:"specialty"`
	Symptoms        string      `json:"symptoms"`
	Status          string      `json:"status"`
	Notes           pgtype.Text `json:"notes"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
	IsOnline        pgtype.Bool `json:"is_online"`
}

type Doctor struct {
	Username       string             `json:"username"`
	Name           string             `json:"name"`
	Email          string             `json:"email"`
	PasswordHash   string             `json:"password_hash"`
	Phone          string             `json:"phone"`
	Gender         string             `json:"gender"`
	Specialization string             `json:"specialization"`
	Qualification  string             `json:"qualification"`
	Experience     int32              `json:"experience"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Patient struct {
	Username     string             `json:"username"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Phone        string             `json:"phone"`
	Age          int32              `json:"age"`
	Gender       string             `json:"gender"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Prescription struct {
	ID                int64       `json:"id"`
	AppointmentID     int64       `json:"appointment_id"`
	PrescriptionText  string      `json:"prescription_text"`
	ConsultationNotes pgtype.Text `json:"consultation_notes"`
	FeedbackRating    pgtype.Int4 `json:"feedback_rating"`
	FeedbackComment   pgtype.Text `json:"feedback_comment"`
	CreatedAt         time.Time   `json:"created_at"`
	UpdatedAt         time.Time   `json:"updated_at"`
}
